baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kruft'
theme="archie"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

